/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Subscriber = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  subscribedAt?: string;
  active?: boolean;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: string;
  publishedAt?: string;
  description?: string;
  tags?: Array<{
    _key: string;
  } & TagReference>;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  } | {
    _key: string;
  } & Code>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Subscriber | Tag | Slug | TagReference | SanityImageAssetReference | Blog | SanityImageCrop | SanityImageHotspot | Code | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../src/lib/queries.ts
// Variable: blogListQuery
// Query: *[	_type == "blog"	&& defined(slug.current)]|order(publishedAt desc)[0...12]{	_id,	title,	slug,	publishedAt,	description,	tags[]->{ name, slug },	coverImage{ asset->{ url } },	images[]{ asset->{ url } }[0...1]}
export type BlogListQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  description: string | null;
  tags: Array<{
    name: string | null;
    slug: Slug | null;
  }> | null;
  coverImage: null;
  images: Array<{
    asset: {
      url: string | null;
    } | null;
  }> | null;
}>;

// Source: ../src/lib/queries.ts
// Variable: blogSlugsQuery
// Query: *[_type == "blog" && defined(slug.current)]{	"params": {"blog": slug.current}}
export type BlogSlugsQueryResult = Array<{
  params: {
    blog: string | null;
  };
}>;

// Source: ../src/lib/queries.ts
// Variable: blogBySlugQuery
// Query: *[_type == "blog" && slug.current == $slug][0]{	title,	author,	publishedAt,	description,	tags[]->{ name, slug },	images[]{ asset->{ url }, alt },	body[]{		...,		_type == "image" => { asset->{ url }, alt, caption },		_type == "code" => { language, code, filename }	}}
export type BlogBySlugQueryResult = {
  title: string | null;
  author: string | null;
  publishedAt: string | null;
  description: string | null;
  tags: Array<{
    name: string | null;
    slug: Slug | null;
  }> | null;
  images: Array<{
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  }> | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "code";
    language: string | null;
    filename: string | null;
    code: string | null;
    highlightedLines?: Array<number>;
  } | {
    asset: {
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    caption: string | null;
    _type: "image";
    _key: string;
  }> | null;
} | null;

// Source: ../src/lib/queries.ts
// Variable: subscriberByEmailQuery
// Query: *[_type == "subscriber" && email == $email][0]
export type SubscriberByEmailQueryResult = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  subscribedAt?: string;
  active?: boolean;
} | null;

// Source: ../src/lib/queries.ts
// Variable: activeSubscribersQuery
// Query: *[_type == "subscriber" && active == true]{ email, active }
export type ActiveSubscribersQueryResult = Array<{
  email: string | null;
  active: true;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    "*[\n\t_type == \"blog\"\n\t&& defined(slug.current)\n]|order(publishedAt desc)[0...12]{\n\t_id,\n\ttitle,\n\tslug,\n\tpublishedAt,\n\tdescription,\n\ttags[]->{ name, slug },\n\tcoverImage{ asset->{ url } },\n\timages[]{ asset->{ url } }[0...1]\n}": BlogListQueryResult;
    "*[_type == \"blog\" && defined(slug.current)]{\n\t\"params\": {\"blog\": slug.current}\n}": BlogSlugsQueryResult;
    "*[_type == \"blog\" && slug.current == $slug][0]{\n\ttitle,\n\tauthor,\n\tpublishedAt,\n\tdescription,\n\ttags[]->{ name, slug },\n\timages[]{ asset->{ url }, alt },\n\tbody[]{\n\t\t...,\n\t\t_type == \"image\" => { asset->{ url }, alt, caption },\n\t\t_type == \"code\" => { language, code, filename }\n\t}\n}": BlogBySlugQueryResult;
    "*[_type == \"subscriber\" && email == $email][0]": SubscriberByEmailQueryResult;
    "*[_type == \"subscriber\" && active == true]{ email, active }": ActiveSubscribersQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}

